namespace: default

db:
  appName: y-db
  image:
    name: mysql
    tag: "8.2.0"
  service:
    port: 3306

api:
  appName: y-api
  image:
    name: larooij/y-api
    tag: latest
  service:
    port: 1323

client:
  appName: y-client
  image:
    name: larooij/y-client
    tag: latest
  service:
    port: 3000
