apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-db-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.db.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appName }}
    spec:
      containers:
      - name: y-db-container
        image: "{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}"
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: y-db-config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: y-db-secret
              key: MYSQL_PASSWORD
        volumeMounts:
          - name: y-db-init
            mountPath: /dockker-entrypoint-initdb.d
          - name: y-db-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: y-db-init
          configMap:
            name: y-db-init-config
        - name: y-db-volume
          persistentVolumeClaim:
            claimName: y-db-pv-claim